
   redis:
      image: redis

   db:
      image: postgres:9.4
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
          #POSTGRES_USERNAME: postgres
          #POSTGRES_PASSWORD: postgres

   vote:
      image: voteapp
      ports:
         - 8085:80
      links:
         - redis

   worker:
      image: workerapp
      links:
         - db
         - redis

   result:
      image: resultapp
      ports:
         - 8086:80
      links:
         - db
